### ISSUE TITLE
Building Terrain Screen Frozen

### ISSUE THREAD

**Issue by BlazingInferno99** [PEMapModder/LegionPE-Public-Resources#11]
Pe I am EzadInferno.Me and ST_David are having the building terrain screen frozen glicth.We cant even use different names.I think there are issues with ip or something.Can u help us

**Comment by PEMapModder** [comment]
Don't create duplication issues.
It is not an issue with the IP. As long as you enter the building terrain screen, a connection is created. It is most likely the problem of PocketMine sending chunks or the world is wrong. Since it sometimes works and sometimes not, it is hard to fix.
