### ISSUE TITLE
Measures against chat flood

### ISSUE THREAD

**Issue by PEMapModder** [PEMapModder/LegionPE-Public-Resources#12]
Which of the following should be implemented?
* chat channels: players will be able to create their own chat channels, particularly useful for teams' chat
* regional chat: players' chat will only be sent to players in the same chat channel within a certain number of blocks' distance

**Comment by Lambo16** [comment]
Chat channels. Regional chat would be annoying in my opinion.

**Comment by PEMapModder** [comment]
The problem is players possibly don't know to use chat channels.
