### ISSUE TITLE
/quit doesn't close spleef session

### ISSUE THREAD

**Issue by WhiteDynamite** [PEMapModder/LegionPE-Public-Resources#14]
If you're playing Spleef and do /quit, then go to KitPvP right after without re logging first, you are unable to attack players, and you're also unable to be attacked.  I also feel that other players can't even see you, but I can't confirm that.

**Comment by VolterVapor** [comment]
Hey... It's Me MC_VolterVapor from LegionPE! Owners, Admins, Bulders, Op, I Have A Big Problem On Legion! My Account Today Is Aurora_Dragunov... Many People Dosent Bekieve To Me That I'm Volt... Everytime My Volt Acc Joins The Loading Of Terrain of Server Stops If Almost done Loading

**Comment by PEMapModder** [comment]
@VolterVapor this place is to report bugs, not for individual support. If you want to have your coordinates file reset, please go to http://PEMapModder.zapto.org/LegionPE/account/delDat.php

**Comment by PEMapModder** [comment]
Fixed
