### ISSUE TITLE
I Have An Issue Im Aurora_Dragunov... Main Account: MC_VolterVapor

### ISSUE THREAD

**Issue by VolterVapor** [PEMapModder/LegionPE-Public-Resources#16]
I have an issue Everytime my MC_VolterVapor account joins... The loading stops if almost done! Volt account is the perfect Acc with Dragunov! Please Help Me I Really Want To Join With My Volt Acc...

**Comment by PEMapModder** [comment]
Only report bugs here. If your own account has a problem, check http://pemapmodder.zapto.org/legionpe/account/delDat.php
