### ISSUE TITLE
words to add to badwords section, "words.json"

### ISSUE THREAD

**Issue by EnderBrine101** [PEMapModder/LegionPE-Public-Resources#23]
Add niqqa, dildo, fak, fack to the bad words list

**Comment by EnderBrine101** [comment]
@PEMapModder Haha, "enhancment" is adding bad words :)

**Comment by PEMapModder** [comment]
"Fak" is not accepted because of "fake". Others are OK; please create a pull request.

**Comment by EnderBrine101** [comment]
Ok

**Comment by EnderBrine101** [comment]
@PEMapModder Done.
