### ISSUE TITLE
Custom weapons through enchantment

### ISSUE THREAD

**Issue by TheMiningGamer32** [PEMapModder/LegionPE-Public-Resources#32]
I am rethinking of a idea:

Players can make their own custom enchants by enchanting. It's like a random gamble:

| tier | coins |
| :-: | :-: |
| tier 1 | 100 coins |
| tier 2 | 500 |
| tier 3 | 1000 |

Custom enchants can even give you something like sharpness V, and if you're unlucky, smite. ~~I hope that this new idea will come soon so me can do our very own weapon~~

**Comment by PEMapModder** [comment]
This is a planned feature in LegionPE Theta.
Already mentioned in #30.
