### ISSUE TITLE
Teleporting for Normal Players

### ISSUE THREAD

**Issue by PEMapModder** [PEMapModder/LegionPE-Public-Resources#8]
This RFC is to propose that the commands `/tpaccept`, `/tpdeny` and `/tprequest` (`/tpa`, `/tpd` and `/tpr`) to be added into LegionPE.

Possibility of Abuses
===
1. Players may abuse it to get away from danger by `/tpr`ing a friend and asking that friend to `/tpa` once he nearly dies.
1. Players may use it to go back to spawn.

Counter Measures against Abuses
===
1. Limit the rate of `/tpr` use by:
  1. Limiting the command to be only used for _x_ times in _y_ seconds
  1. Limiting the command to be only used for _x_ times in one session
1. Disallow players who are at spawn to use `/tpa`
1. Delay execution or `/tpa`

**Comment by EnderBrine101** [comment]
Disable at spawn

**Comment by PEMapModder** [comment]
Already done. Do you even play on the server...

**Comment by EnderBrine101** [comment]
Its always full when I join D:

**Comment by PEMapModder** [comment]
@EnderBrine101 this place is a bug tracker, not a forum or support channel. If you continue commenting meaninglessly, you **will** be blocked from my GitHub repos.

**Comment by EnderBrine101** [comment]
There is 
 No forum @PEMapModder

**Comment by PEMapModder** [comment]
Then don't try to find a forum.
